// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb16xncBqX3uiM_PIVceWyw0-diQlwT1g',
    appId: '1:931147776998:web:af79332d04aee7179d4c27',
    messagingSenderId: '931147776998',
    projectId: 'beauty-and-cosmetics-8513a',
    authDomain: 'beauty-and-cosmetics-8513a.firebaseapp.com',
    storageBucket: 'beauty-and-cosmetics-8513a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy1sA8hXknzaZue9xiPSFSVLQ5xjoGm3w',
    appId: '1:931147776998:android:bc60398e359ea2739d4c27',
    messagingSenderId: '931147776998',
    projectId: 'beauty-and-cosmetics-8513a',
    storageBucket: 'beauty-and-cosmetics-8513a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTfcCiTKwI671CdOCYKFeF-tl7uLkupxU',
    appId: '1:931147776998:ios:c1aed701819c246a9d4c27',
    messagingSenderId: '931147776998',
    projectId: 'beauty-and-cosmetics-8513a',
    storageBucket: 'beauty-and-cosmetics-8513a.firebasestorage.app',
    iosClientId: '931147776998-q7ch9ief4kffrf1pf0lusdqcn9i2kfje.apps.googleusercontent.com',
    iosBundleId: 'com.example.beautyCosmetics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTfcCiTKwI671CdOCYKFeF-tl7uLkupxU',
    appId: '1:931147776998:ios:c1aed701819c246a9d4c27',
    messagingSenderId: '931147776998',
    projectId: 'beauty-and-cosmetics-8513a',
    storageBucket: 'beauty-and-cosmetics-8513a.firebasestorage.app',
    iosClientId: '931147776998-q7ch9ief4kffrf1pf0lusdqcn9i2kfje.apps.googleusercontent.com',
    iosBundleId: 'com.example.beautyCosmetics',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDb16xncBqX3uiM_PIVceWyw0-diQlwT1g',
    appId: '1:931147776998:web:75ca483efbbf092d9d4c27',
    messagingSenderId: '931147776998',
    projectId: 'beauty-and-cosmetics-8513a',
    authDomain: 'beauty-and-cosmetics-8513a.firebaseapp.com',
    storageBucket: 'beauty-and-cosmetics-8513a.firebasestorage.app',
  );
}
